#!/bin/sh
set -e
case "$1" in
    remove|purge)
        if [ -d /run/systemd/system ]; then
            systemctl daemon-reload
        fi
        rm -f /boot/sl7/7.2.0-5-sl7/initrd.img /boot/sl7/7.2.0-5-sl7/initrd.img.new
        rmdir /boot/sl7/7.2.0-5-sl7 2>/dev/null || true
        if [ -x /usr/sbin/update-grub ]; then
            update-grub
        fi
        ;;
esac
